"""
Check the explanation, not just the result.

`run_demo.py` shows that the conclusion does not survive. The README then
explains *why*, and that explanation makes factual claims about this data. An
explanation that sounds right and was never measured is exactly the failure this
repo exists to argue against, so each claim is stated and measured here.

The claims:

  1. The negative control really does keep every column intact. It is supposed to
     leave each column's own distribution untouched and destroy only how the
     columns line up. If it fails that, it is not a clean control.
  2. The simulator's own fidelity check really does pass. The claim that anyone
     would have shipped this data rests on it.
  3. The relationship being lost is a jump, not a trend. A method that ties
     columns together with a single number can express a trend and cannot express
     a jump, which is the mechanism being blamed.
  4. The simulator flattens that jump. This is the claimed cause of the
     coefficient coming back too small.

Run from the repo root:  python examples/decision_check/mechanism_check.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from simulate.generate import generate_table

HERE = Path(__file__).resolve().parent
CSV = HERE / "credit_default.csv"
PREDICTORS = ["pay_delay_1", "utilization", "log_limit", "age"]
OUTCOME = "default"
CLIFF_AT = 2
# Match run_demo.py exactly. Two scripts describing the same synthetic table must
# generate it the same way, or they report different numbers for one thing.
SEED = 1
N = None          # same row count as the real table, as run_demo does


def outcome_rate_by_delay(frame: pd.DataFrame) -> pd.Series:
    """Share of accounts that default, by how many periods behind they are."""
    d = frame[frame["pay_delay_1"].between(-2, 4)]
    g = d.groupby(d["pay_delay_1"].round().astype(int))[OUTCOME]
    return g.mean()[g.count() >= 30]


def largest_column_gap(real: pd.DataFrame, synth: pd.DataFrame) -> tuple[str, float]:
    """Biggest difference between a real and synthetic column, as a share."""
    from scipy.stats import ks_2samp
    gaps = {c: float(ks_2samp(real[c].to_numpy(), synth[c].to_numpy()).statistic)
            for c in PREDICTORS}
    worst = max(gaps, key=gaps.get)
    return worst, gaps[worst]


def main():
    real = pd.read_csv(CSV)
    result = generate_table(real, n_rows=N or len(real), seed=SEED,
                            table_name="real_table")
    sim = result.synthetic_df

    rng = np.random.default_rng(3)   # same shuffle seed as run_demo
    shuffled = sim.copy()
    for c in shuffled.columns:
        shuffled[c] = rng.permutation(shuffled[c].to_numpy())

    verdicts = []
    lines = ["<!-- Generated by examples/decision_check/mechanism_check.py. Do not edit. -->",
             "", "# Is the explanation true?", "",
             "The README explains why the conclusion does not survive. These are the",
             "factual claims that explanation rests on, each one measured.", ""]

    # 1. the negative control keeps every column intact
    col, gap = largest_column_gap(sim, shuffled)
    ok = gap < 0.01
    verdicts.append(("Negative control leaves every column intact", ok))
    print(f"1. largest column change after shuffling: {gap:.4f} (worst: {col})")
    lines += ["## 1. The negative control keeps every column intact", "",
              f"Shuffling each column on its own should change no column's own",
              f"distribution at all. Largest change across the four predictors: "
              f"**{gap:.4f}** (`{col}`).", "",
              ("Holds. The columns are untouched, so everything it breaks is about how "
               "the columns line up with each other, which is what makes it a clean "
               "control." if ok else "**Does not hold.** The shuffle is changing the "
               "columns themselves, so it is not isolating what it claims to."), ""]

    # 2. the simulator's own fidelity check passes
    ok = bool(result.fidelity_passed)
    verdicts.append(("The simulator's own check passes", ok))
    print(f"2. fidelity_passed={result.fidelity_passed}  "
          f"correlation delta={result.correlation_delta:.3f}")
    lines += ["## 2. The simulator's own check passes", "",
              f"`fidelity_passed` is **{result.fidelity_passed}**, with a correlation "
              f"shift of **{result.correlation_delta:.3f}**.", "",
              ("Holds. The data clears the repo's own quality gate, so anyone relying "
               "on that verdict alone would have shipped it." if ok else
               "**Does not hold.** The data does not pass, so the claim that it would "
               "have been shipped is not supported."), ""]

    # 3. it is a jump, not a trend
    rate = outcome_rate_by_delay(real)
    below = rate[rate.index < CLIFF_AT].mean()
    above = rate[rate.index >= CLIFF_AT].mean()
    jump = float(above - below)
    biggest_step_at = int(rate.diff().dropna().idxmax())
    ok = jump > 0.20 and biggest_step_at == CLIFF_AT
    verdicts.append(("The relationship is a jump, not a trend", ok))
    print(f"3. default rate by periods behind:\n{rate.round(3).to_string()}")
    lines += ["## 3. The relationship is a jump, not a trend", "",
              "Share of accounts that default, by how many periods behind they are:", "",
              "| periods behind | defaults |", "|---|---|"]
    lines += [f"| {k} | {v:.3f} |" for k, v in rate.items()]
    lines += ["",
              f"Average below the {CLIFF_AT}-period line is {below:.3f}, above it "
              f"{above:.3f}, a gap of **{jump:+.3f}**, and the largest single step is "
              f"at {biggest_step_at}.", "",
              ("Holds. Risk climbs and then jumps. A single number describing how two "
               "columns move together can describe a climb and cannot describe a jump."
               if ok else "**Does not hold** as stated."), ""]

    # 4. the simulator flattens it
    real_corr = float(real["pay_delay_1"].corr(real[OUTCOME]))
    sim_corr = float(sim["pay_delay_1"].corr(sim[OUTCOME]))
    sim_rate = outcome_rate_by_delay(sim)
    sim_jump = float(sim_rate[sim_rate.index >= CLIFF_AT].mean()
                     - sim_rate[sim_rate.index < CLIFF_AT].mean())
    ok = sim_jump < jump and sim_corr < real_corr
    verdicts.append(("The simulator flattens the jump", ok))
    print(f"4. real corr={real_corr:+.3f} gap={jump:+.3f}  |  "
          f"simulated corr={sim_corr:+.3f} gap={sim_jump:+.3f}")
    lines += ["## 4. The simulator flattens the jump", "",
              "| | correlation with the outcome | size of the jump |", "|---|---|---|",
              f"| real data | {real_corr:+.3f} | {jump:+.3f} |",
              f"| simulated | {sim_corr:+.3f} | {sim_jump:+.3f} |", "",
              (f"Holds. The jump comes out smaller than it is, which is why the "
               f"coefficient comes back too small." if ok else
               "**Does not hold.** The flattening explanation is not supported."), "",
              "## Verdict", "", "| claim | measured |", "|---|---|"]
    for name, v in verdicts:
        lines.append(f"| {name} | {'holds' if v else '**does not hold**'} |")
    lines.append("")

    (HERE / "MECHANISM.md").write_text("\n".join(lines))
    print("\nVerdicts:")
    for name, v in verdicts:
        print(f"   {'PASS' if v else 'FAIL'}  {name}")
    print(f"\nTable → {(HERE / 'MECHANISM.md').name}")


if __name__ == "__main__":
    main()
